name: Validate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Validate with HACS
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Validate with Hassfest
        uses: home-assistant/actions/hassfest@master
